namespace ArduinoSimulator.Enums
{
    public enum ArduinoKeys : uint
    {
        KEY_LEFT_CTRL = 0x80,
        KEY_LEFT_SHIFT = 0x81,
        KEY_LEFT_ALT = 0x82,
        KEY_LEFT_GUI = 0x83,
        KEY_RIGHT_CTRL = 0x84,
        KEY_RIGHT_SHIFT = 0x85,
        KEY_RIGHT_ALT = 0x86,
        KEY_RIGHT_GUI = 0x87,

        KEY_UP_ARROW = 0xDA,
        KEY_DOWN_ARROW = 0xD9,
        KEY_LEFT_ARROW = 0xD8,
        KEY_RIGHT_ARROW = 0xD7,
        KEY_BACKSPACE = 0xB2,
        KEY_TAB = 0xB3,
        KEY_RETURN = 0xB0,
        KEY_MENU = 0xED,
        KEY_ESC = 0xB1,
        KEY_INSERT = 0xD1,
        KEY_DELETE = 0xD4,
        KEY_PAGE_UP = 0xD3,
        KEY_PAGE_DOWN = 0xD6,
        KEY_HOME = 0xD2,
        KEY_END = 0xD5,
        KEY_CAPS_LOCK = 0xC1,
        KEY_PRINT_SCREEN = 0xCE,
        KEY_SCROLL_LOCK = 0xCF,
        KEY_PAUSE = 0xD0,

        KEY_NUM_LOCK = 0xDB,
        KEY_KP_SLASH = 0xDC,
        KEY_KP_ASTERISK = 0xDD,
        KEY_KP_MINUS = 0xDE,
        KEY_KP_PLUS = 0xDF,
        KEY_KP_ENTER = 0xE0,
        KEY_KP_1 = 0xE1,
        KEY_KP_2 = 0xE2,
        KEY_KP_3 = 0xE3,
        KEY_KP_4 = 0xE4,
        KEY_KP_5 = 0xE5,
        KEY_KP_6 = 0xE6,
        KEY_KP_7 = 0xE7,
        KEY_KP_8 = 0xE8,
        KEY_KP_9 = 0xE9,
        KEY_KP_0 = 0xEA,
        KEY_KP_DOT = 0xEB,
    }
}
